<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\OrdenPedido;

class OrdenPedidosSeeder extends Seeder
{
    public function run()
    {
        OrdenPedido::create([
            'id' => 1,
            'id_op' => 'OP-GES-1-1',
            'id_empresa' => null,
            'fecha_orden_pedido' => '2024-02-09',
            'fecha_programacion' => '2024-01-10',
            'tipo_envio' => 'total',
            'id_proveedor' => '22',
            'contacto_proveedor' => '31',
            'nota_pedido' => null,
            'fecha_recepcion' => '2024-01-10',
            'tipo_pago' => 'Pago al Contado',
            'nota_pago' => null,
            'etiquetado' => null,
            'embalaje' => null,
            'observaciones' => null,
            'total_proveedor' => 2112.20,
            'id_transporte' => null,
            'contacto_transporte' => null,
            'cot_transporte' => '0.00',
            'flete' => '0.00',
            't_departamento' => null,
            't_provincia' => null,
            't_distrito' => null,
            't_direccion' => null,
            'transporte_nota' => null,
            't_factura' => null,
            't_grt' => null,
            't_fecha_pago' => null,
            'estado_op' => 'conforme',
            'fecha_entrega' => '2024-01-10',
            'retorno_mercaderia' => 'ninguno',
            'cargo_oea' => null,
            'nota_op' => null,
            'id_seguimiento' => 1,
            'updated_at' => '2024-02-09 23:27:31',
            'created_at' => null,
        ]);

        OrdenPedido::create([
            'id' => 2,
            'id_op' => 'OP-GES-2-1',
            'id_empresa' => null,
            'fecha_orden_pedido' => '2024-02-09',
            'fecha_programacion' => '2024-01-11',
            'tipo_envio' => 'total',
            'id_proveedor' => '82',
            'contacto_proveedor' => '37',
            'nota_pedido' => null,
            'fecha_recepcion' => '2024-01-11',
            'tipo_pago' => 'Pago al Contado',
            'nota_pago' => null,
            'etiquetado' => null,
            'embalaje' => null,
            'observaciones' => 'SE ENTREGARA UN ADICIONAL DE 5 PAQUETES (GESTION TRIBUTARIA ASUME 3 PAQUETES COMO INDICA EL PEDIDO Y DARYZA ASUME 2 PAQUETES)',
            'total_proveedor' => 33431.50,
            'id_transporte' => null,
            'contacto_transporte' => null,
            'cot_transporte' => '0.00',
            'flete' => '0.00',
            't_departamento' => null,
            't_provincia' => null,
            't_distrito' => null,
            't_direccion' => null,
            'transporte_nota' => null,
            't_factura' => null,
            't_grt' => null,
            't_fecha_pago' => null,
            'estado_op' => 'conforme',
            'fecha_entrega' => '2024-01-11',
            'retorno_mercaderia' => 'ninguno',
            'cargo_oea' => null,
            'nota_op' => null,
            'id_seguimiento' => 2,
            'updated_at' => '2024-02-09 23:28:44',
            'created_at' => null,
        ]);

        OrdenPedido::create([
            'id' => 4,
            'id_op' => 'OP-GES-4-1',
            'id_empresa' => null,
            'fecha_orden_pedido' => '2024-02-09',
            'fecha_programacion' => '2024-01-22',
            'tipo_envio' => 'total',
            'id_proveedor' => '8',
            'contacto_proveedor' => '32',
            'nota_pedido' => null,
            'fecha_recepcion' => '2024-01-22',
            'tipo_pago' => 'Pago al Contado',
            'nota_pago' => null,
            'etiquetado' => null,
            'embalaje' => null,
            'observaciones' => null,
            'total_proveedor' => 6950.00,
            'id_transporte' => 4,
            'contacto_transporte' => '9',
            'cot_transporte' => '556.00',
            'flete' => '18.00',
            't_departamento' => 'LIMA',
            't_provincia' => 'LIMA',
            't_distrito' => 'ATE',
            't_direccion' => 'AV. EVITAMIENTO MZ. B LOTE 12 Y 13 - ATE 1502',
            'transporte_nota' => '2 SOLES POR TOALLA',
            't_factura' => 'F008-00120121',
            't_grt' => 'V008-007677',
            't_fecha_pago' => '2024-02-05',
            'estado_op' => 'conforme',
            'fecha_entrega' => '2024-01-24',
            'retorno_mercaderia' => 'ninguno',
            'cargo_oea' => null,
            'nota_op' => null,
            'id_seguimiento' => 4,
            'updated_at' => '2024-02-10 15:38:31',
            'created_at' => null,
        ]);

        OrdenPedido::create([
            'id' => 5,
            'id_op' => 'OP-GES-5-1',
            'id_empresa' => null,
            'fecha_orden_pedido' => '2024-02-09',
            'fecha_programacion' => '2024-01-22',
            'tipo_envio' => 'total',
            'id_proveedor' => '8',
            'contacto_proveedor' => '32',
            'nota_pedido' => null,
            'fecha_recepcion' => '2024-01-22',
            'tipo_pago' => 'Pago al Contado',
            'nota_pago' => null,
            'etiquetado' => null,
            'embalaje' => null,
            'observaciones' => null,
            'total_proveedor' => 2800.00,
            'id_transporte' => 64,
            'contacto_transporte' => '24',
            'cot_transporte' => '336.00',
            'flete' => '35.00',
            't_departamento' => 'AREQUIPA',
            't_provincia' => 'AREQUIPA',
            't_distrito' => 'AREQUIPA',
            't_direccion' => 'JR. HUMBOLDT 701 - La Victoria',
            'transporte_nota' => '3 soles por toalla',
            't_factura' => 'F111 N° 00005005',
            't_grt' => 'V019 - 25824',
            't_fecha_pago' => '2024-01-23',
            'estado_op' => 'conforme',
            'fecha_entrega' => '2024-01-24',
            'retorno_mercaderia' => 'ninguno',
            'cargo_oea' => '-',
            'nota_op' => '-',
            'id_seguimiento' => 5,
            'updated_at' => '2024-02-13 14:42:31',
            'created_at' => null,
        ]);
    }
}
