<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Seguimiento;

class SeguimientosSeeder extends Seeder
{
    public function run()
    {
        Seguimiento::insert([
            [
                'fecha_emision' => '2024-02-09',
                'oce_doc_path' => 'public/doc/OCAM-2024-200035-2-0.pdf',
                'ocf_doc_path' => 'public/doc/20100116392',
                'id_empresa' => 7,
                'id_cliente' => 584,
                'catalogo' => 'EXT-CE-2021-3',
                'fecha_form' => '2024-01-05',
                'fecha_max_form' => '2024-01-15',
                'monto_venta' => 2346.78,
                'siaf' => 'NO APLICA',
                'cprovincia' => 'LIMA',
                'cdistrito' => 'SAN ISIDRO',
                'cdepartamento' => 'LIMA',
                'cdireccion' => 'CALLE AUGUSTO TAMAYO 160',
                'creferencia' => 'ALTURA DEL PUENTE CORPORAC DE VIA EXPRESA',
                'productos' => '20 PAPEL TOALLA: INTERFOLIADO-NATURAL',
                'etapa_siaf' => 'PAG',
                'fecha_siaf' => '2024-01-19',
                'factura' => 'FA01-2446',
                'fecha_factura' => '2024-01-09',
                'grr' => 'TA01-1761',
                'retencion' => '0',
                'detraccion' => '0',
                'forma_envio' => null,
                're_factura' => null,
                're_fecha_factura' => null,
                're_grr' => null,
                're_retencion' => null,
                're_detraccion' => null,
                're_forma_envio' => null,
                'nota_credito' => '0',
                'id_venta' => 'OC-GES-1',
                'contacto_cliente' => '111',
                'op_proveedor' => 2112.20,
                'cargo_entrega' => 'public/doc/CORPORACIÓN FINANCIERA.pdf',
                'peru_compras' => '4500002734-2024.pdf',
                'fecha_peru_compras' => '2024-01-10',
                'fecha_entrega_oc' => '2024-01-10',
                'contacto_cobrador' => '28',
                'monto_retencion' => '0.00',
                'monto_detraccion' => '0.00',
                'penalidad' => 0.00,
                'neto_cobrado' => '2346.78',
                'estado_moroza' => null,
                'fecha_cobro' => '2024-02-12',
                'proxima_gestion' => null,
                'estado_activo' => 1,
                'estado_facturacion' => 4,
                'estado_tesoreria' => null,
                'inicio_cobranza' => '2024-02-09 18:27:31',
                'fin_cobranza' => '2024-06-22 12:41:00'
            ],
            [
                'fecha_emision' => '2024-02-09',
                'oce' => 'public/doc/OCAM-2024-157-1-0.pdf',
                'ocf' => 'public/doc/20131373075',
                'id_empresa' => 7,
                'id_cliente' => 585,
                'catalogo' => 'EXT-CE-2021-3',
                'fecha_form' => '2024-01-05',
                'fecha_max_form' => '2024-01-23',
                'monto_venta' => 36827.21,
                'siaf' => 'NO APLICA',
                'cprovincia' => 'LIMA',
                'cdistrito' => 'LA MOLINA', // Cerrar cadena aquí
                'cdepartamento' => 'LIMA',
                'cdireccion' => 'AV. LOS CEDROS 1234',
                'creferencia' => 'CERCA DEL CENTRO COMERCIAL',
                'productos' => '50 LAPTOPS: CORE i5',
                'etapa_siaf' => 'REG',
                'fecha_siaf' => '2024-01-20',
                'factura' => 'FA02-1243',
                'fecha_factura' => '2024-01-15',
                'grr' => 'TA02-1234',
                'retencion' => '0',
                'detraccion' => '0',
                'forma_envio' => null,
                're_factura' => null,
                're_fecha_factura' => null,
                're_grr' => null,
                're_retencion' => null,
                're_detraccion' => null,
                're_forma_envio' => null,
                'nota_credito' => '0',
                'id_venta' => 'OC-GES-2',
                'contacto_cliente' => '112',
                'op_proveedor' => 34271.00,
                'cargo_entrega' => 'public/doc/FINANCIERA_PROV.pdf',
                'peru_compras' => '4500001234-2024.pdf',
                'fecha_peru_compras' => '2024-01-15',
                'fecha_entrega_oc' => '2024-01-20',
                'contacto_cobrador' => '30',
                'monto_retencion' => '0.00',
                'monto_detraccion' => '0.00',
                'penalidad' => 0.00,
                'neto_cobrado' => '36827.21',
                'estado_moroza' => null,
                'fecha_cobro' => '2024-02-20',
                'proxima_gestion' => null,
                'estado_activo' => 1,
                'estado_facturacion' => 5,
                'estado_tesoreria' => null,
                'inicio_cobranza' => '2024-02-09 18:27:31',
                'fin_cobranza' => '2024-06-22 12:41:00'
            ]
        ]);
    }
}
